SELECT 
    FACULTY.FACULTY_NAME,
    PULPIT.PULPIT_NAME,
    PROFESSION.PROFESSION_NAME,
    SUBJECT.SUBJECT_NAME,
    STUDENT.NAME,
    CASE
        WHEN (PROGRESS.NOTE = 6) THEN 'רוסעü'
        WHEN (PROGRESS.NOTE = 7) THEN 'סולü'
        WHEN (PROGRESS.NOTE = 8) THEN 'גמסולü'
    end as 'GRADE'
FROM 
    PROGRESS INNER JOIN STUDENT
    ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
    INNER JOIN GROUPS
    ON STUDENT.IDGROUP = GROUPS.IDGROUP
    INNER JOIN FACULTY
    ON GROUPS.FACULTY = FACULTY.FACULTY
    INNER JOIN PROFESSION
    ON GROUPS.PROFESSION = PROFESSION.PROFESSION
    INNER JOIN SUBJECT
    ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
    INNER JOIN PULPIT
    ON SUBJECT.PULPIT = PULPIT.PULPIT
WHERE 
    PROGRESS.NOTE BETWEEN 6 AND 8
ORDER BY 
    PROGRESS.NOTE DESC;