SELECT 
    AUDITORIUM.AUDITORIUM,
    AUDITORIUM.AUDITORIUM_NAME,
    AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM 
    AUDITORIUM 
INNER JOIN 
    AUDITORIUM_TYPE ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
WHERE 
    AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE '%компьютер%'
ORDER BY 
    AUDITORIUM.AUDITORIUM;